package com.hiilimonoksidi.tiralabra.application.gui;

import com.hiilimonoksidi.tiralabra.misc.Point;
import com.hiilimonoksidi.tiralabra.pathfinding.PathfindingAlgorithm;
import java.awt.image.BufferedImage;
import javax.swing.DefaultListModel;

/**
 *
 * @author Janne Ruoho
 */
public class AlgorithmTestingPanel extends javax.swing.JPanel {

    private BufferedImage originalImage;
    private Point start, end;

    public AlgorithmTestingPanel(BufferedImage image, Point start, Point end) {
        initComponents();
        originalImage = image;
        this.start = start;
        this.end = end;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelResults = new javax.swing.JPanel();
        jScrollPaneResults = new javax.swing.JScrollPane();
        jTextAreaResults = new javax.swing.JTextArea();
        jPanelOptions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneAlgorithms = new javax.swing.JScrollPane();
        jListAlgorithms = new javax.swing.JList();
        jCheckBoxVisualize = new javax.swing.JCheckBox();
        jButtonStart = new javax.swing.JButton();
        jSliderSpeed = new javax.swing.JSlider();
        jLabelSpeed = new javax.swing.JLabel();
        jLabelTimeLimit = new javax.swing.JLabel();
        jTextFieldTimeLimit = new javax.swing.JTextField();
        jLabelSeconds = new javax.swing.JLabel();
        jPanelImage = new javax.swing.JPanel();
        jScrollPaneCanvas = new javax.swing.JScrollPane();
        jPanelCanvas = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanelResults.setLayout(new java.awt.GridBagLayout());

        jScrollPaneResults.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneResults.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaResults.setEditable(false);
        jTextAreaResults.setColumns(20);
        jTextAreaResults.setRows(5);
        jScrollPaneResults.setViewportView(jTextAreaResults);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelResults.add(jScrollPaneResults, gridBagConstraints);

        add(jPanelResults, java.awt.BorderLayout.PAGE_END);

        jPanelOptions.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Select algorithm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanelOptions.add(jLabel1, gridBagConstraints);

        DefaultListModel<PathfindingAlgorithm.Type> listModel = new DefaultListModel<>();
        for (PathfindingAlgorithm.Type algo : PathfindingAlgorithm.Type.values()) {
            listModel.addElement(algo);
        }
        jListAlgorithms.setModel(listModel);
        jListAlgorithms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneAlgorithms.setViewportView(jListAlgorithms);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanelOptions.add(jScrollPaneAlgorithms, gridBagConstraints);

        jCheckBoxVisualize.setText("Visualize (no timing)");
        jCheckBoxVisualize.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxVisualizeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 15);
        jPanelOptions.add(jCheckBoxVisualize, gridBagConstraints);

        jButtonStart.setText("Start");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 5);
        jPanelOptions.add(jButtonStart, gridBagConstraints);

        jSliderSpeed.setEnabled(false);
        jSliderSpeed.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanelOptions.add(jSliderSpeed, gridBagConstraints);

        jLabelSpeed.setText("Speed:");
        jLabelSpeed.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanelOptions.add(jLabelSpeed, gridBagConstraints);

        jLabelTimeLimit.setText("Time limit:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanelOptions.add(jLabelTimeLimit, gridBagConstraints);

        jTextFieldTimeLimit.setColumns(5);
        jTextFieldTimeLimit.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanelOptions.add(jTextFieldTimeLimit, gridBagConstraints);

        jLabelSeconds.setText("seconds");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanelOptions.add(jLabelSeconds, gridBagConstraints);

        add(jPanelOptions, java.awt.BorderLayout.LINE_END);

        jPanelImage.setLayout(new java.awt.GridBagLayout());

        jPanelCanvas.setLayout(new java.awt.GridBagLayout());
        jScrollPaneCanvas.setViewportView(jPanelCanvas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelImage.add(jScrollPaneCanvas, gridBagConstraints);

        add(jPanelImage, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxVisualizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxVisualizeStateChanged
        boolean s = jCheckBoxVisualize.isSelected();
        jLabelSpeed.setEnabled(s);
        jSliderSpeed.setEnabled(s);
        jLabelTimeLimit.setEnabled(!s);
        jTextFieldTimeLimit.setEnabled(!s);
        jLabelSeconds.setEnabled(!s);
    }//GEN-LAST:event_jCheckBoxVisualizeStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JCheckBox jCheckBoxVisualize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSeconds;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JLabel jLabelTimeLimit;
    private javax.swing.JList jListAlgorithms;
    private javax.swing.JPanel jPanelCanvas;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JScrollPane jScrollPaneAlgorithms;
    private javax.swing.JScrollPane jScrollPaneCanvas;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JSlider jSliderSpeed;
    private javax.swing.JTextArea jTextAreaResults;
    private javax.swing.JTextField jTextFieldTimeLimit;
    // End of variables declaration//GEN-END:variables
}
